FROM php:8.2-cli-alpine

# Install necessary system dependencies for librdkafka
RUN apk add --no-cache \
    librdkafka-dev \
    build-base \
    autoconf

# Install the php-rdkafka extension
# Use pecl install for easy installation
RUN pecl install rdkafka \
    && docker-php-ext-enable rdkafka

COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

WORKDIR /app